### ISSUE TITLE
Groq API KEY Generation

### ISSUE THREAD

**Issue by gitdevjin** [AnhChienVu/VShell#2]
In your instruction of installing and using your tool.
There is this:
2. Create a Groq API Key.

I think it would be more helpful to leave a link to the Groq page where people can generate API KEY
And also, how to set up the `.env` file, like the environment variable. Although I can find in your code, I cannot know the environment variable from your instruction.

`GROQ_API_KEY` is the environment variable so probably you can write in the README.md

So, it would look like

```console
#.env file
GROQ_API_KEY=your_groq_api_key
```

**Comment by AnhChienVu** [comment]
I added the way to set up API Key in .env
