### ISSUE TITLE
`npm link` still doesn't work

### ISSUE THREAD

**Issue by gitdevjin** [AnhChienVu/VShell#5]
Hi Anh. I pulled your latest repo, but
the commend in the instruction `npm link` still doesn't work, and I can't run the tool with the commend `vshell <file>`

<img width="1116" alt="Screenshot 2024-09-13 at 9 53 24 AM" src="https://github.com/user-attachments/assets/ace44fc8-7abb-4608-a1a5-d4d9ef3080fc">

**Comment by AnhChienVu** [comment]
Can you run this command before npm link: 
```npm install -g .```

**Comment by AnhChienVu** [comment]
I just noticed you are using Macbook right, so for Mac, you have to make sure setting that file executable before running npm link.
If it still not work, you can try:
```sudo npm link```
