### ISSUE TITLE
issue with `output` Option

### ISSUE THREAD

**Issue by gitdevjin** [AnhChienVu/VShell#8]
I think `-output` option is not working
I think this option is supposed to generate an output file, but I don't see any file that is generated when I don't enter a file name. I can only see the result on the stdout(on console).
And also, when I enter a file name, it gives an error:
<img width="976" alt="Screenshot 2024-09-19 at 9 36 35 AM" src="https://github.com/user-attachments/assets/b4b32bd2-d2bc-4b26-8dc5-165bd547239e">

**Comment by AnhChienVu** [comment]
I just fixed it by changing the name that corresponds to the output's options object:
Here is the option for output: 
![image](https://github.com/user-attachments/assets/56a4840b-6b43-4607-b131-bdb0f0d1be5e)
And I fixed it in ai.js file:
Before: 
![image](https://github.com/user-attachments/assets/1d8e2ba2-5b4b-4fac-a24b-7c0b95ad739c)
After fixed:
![image](https://github.com/user-attachments/assets/b03a9eb9-f413-4977-bb13-8007016be0db)

**Comment by gitdevjin** [comment]
I synced your latest repo and tried it again, but I think the issue is still persisting
<img width="978" alt="Screenshot 2024-09-20 at 12 24 02 PM" src="https://github.com/user-attachments/assets/29681ae8-8924-4912-8b2d-2fbc7a5f3671">
