### ISSUE TITLE
issue with the purpose of the program (README.md and the result)

### ISSUE THREAD

**Issue by gitdevjin** [AnhChienVu/VShell#9]
From your `README.md` file, I still cannot understand what exactly this tool is for.
And also, I can't even guess from the output result generated by this tool.
It gives completely different result from the original file.
For example, I used a file with the following content.
```
#test.txt file
Hello World!
This is test text
```
And the tool gave me this result,
<img width="1220" alt="Screenshot 2024-09-19 at 9 23 02 AM" src="https://github.com/user-attachments/assets/0de0b2db-13ff-453c-ba4a-7db468d77e78">
<img width="1215" alt="Screenshot 2024-09-19 at 9 23 09 AM" src="https://github.com/user-attachments/assets/170bfbd2-c994-40ec-93d4-041c5f50a80a">

**Comment by AnhChienVu** [comment]
I think you were testing by the old version that I didn't make any changes to the prompt that I asked Groq to generate a response that follow my template. If you pull the updated version of my repo now. Here is the response that Groq returns:
# Understanding `test.txt` File

## Project Structure

```
.
test.txt
```

## test.txt

The `test.txt` file is a simple text file that contains a greeting and a message. It does not contain any executable code, and its purpose is to serve as a data file.

### Contents of the File

The file starts with a greeting "Hello World!" followed by a message "This is test text".
